// src/components/Layout.vue
<template>
  <main class="f-full h-full overflow-hidden relative">
    <layout-header />
    <layout-content>
      <slot></slot>
    </layout-content>
    <layout-footer />
  </main>
</template>

<script setup>
import LayoutHeader from './Layout/Header.vue'
import LayoutContent from './Layout/Content.vue'
import LayoutFooter from './Layout/Footer.vue'
</script>

// src/components/Layout.jsx
import Header from './Layout/Header'
import Content from './Layout/Content'
import Footer from './Layout/Footer'

const Layout = ({ children }) => {
  return (
    <main className='f-full h-full overflow-hidden relative'>
      <Header />
      <Content>{children}</Content>
      <Footer />
    </main>
  )
}

export default Layout
